FROM arm64v8/gradle:8.3-jdk17 AS build
WORKDIR /app
COPY build.gradle settings.gradle /app/
COPY config /app/config
COPY src /app/src
RUN gradle build

FROM amazoncorretto:17-alpine3.18-jdk
WORKDIR /app
COPY --from=build /app/build/libs/todo-service.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
