INSERT INTO TODO (ID, DESCRIPTION, STATUS, CREATED_AT, UPDATED_AT, DUE_AT) (1, "Description 1", 1, CURRENT_TIMESTAMP(), null, null);
INSERT INTO TODO (ID, DESCRIPTION, STATUS, CREATED_AT, UPDATED_AT, DUE_AT) (2, "Description 2", 1, CURRENT_TIMESTAMP(), null, null);
INSERT INTO TODO (ID, DESCRIPTION, STATUS, CREATED_AT, UPDATED_AT, DUE_AT) (3, "Description 3", 1, CURRENT_TIMESTAMP(), null, null);
INSERT INTO TODO (ID, DESCRIPTION, STATUS, CREATED_AT, UPDATED_AT, DUE_AT) (4, "Description 4", 1, CURRENT_TIMESTAMP(), null, null);
INSERT INTO TODO (ID, DESCRIPTION, STATUS, CREATED_AT, UPDATED_AT, DUE_AT) (5, "Description 5", 1, CURRENT_TIMESTAMP(), null, null);



